"""
EduGemma - Supplementary Training Data (Volume 2)
Adds ~400 more examples to reach 500+ target
Focus: biology, CS, geometry, and more depth in core subjects
"""

# These will be appended to the main generator's ENTRIES list
# Topics: algebra, calculus, physics, chemistry, geometry, biology, cs
# Format: (question, answer, topic, difficulty)

SUPPLEMENT = [

# ============================================================
# BIOLOGY (45 examples - was 5, target 50)
# ============================================================
    ("What is a cell?", "A cell is the basic unit of life — the smallest thing that can be considered alive.\n\nTwo main types:\n- Prokaryotic: No nucleus (bacteria, archaea). Simple, small.\n- Eukaryotic: Has a nucleus (plants, animals, fungi). Complex, larger.\n\nEvery cell has:\n- Cell membrane: Controls what enters and leaves\n- Cytoplasm: Jelly-like interior where reactions happen\n- DNA: Genetic instructions\n- Ribosomes: Make proteins\n\nEukaryotic cells also have:\n- Nucleus: Houses DNA\n- Mitochondria: Power plant (makes ATP)\n- Endoplasmic reticulum: Protein/lipid factory\n- Golgi apparatus: Packages and ships proteins\n\nYour body has ~37 trillion cells, each doing its specific job.", "biology", 1),
    ("What is mitosis?", "Mitosis is cell division that creates two identical copies.\n\nPhases (PMAT):\n1. Prophase: Chromosomes condense, nuclear membrane breaks down\n2. Metaphase: Chromosomes line up at the center (equator)\n3. Anaphase: Chromosomes pull apart to opposite sides\n4. Telophase: Two new nuclei form, cells start to split\n\nThen cytokinesis: the cell actually divides into two.\n\nResult: 2 daughter cells, each with the same 46 chromosomes as the parent.\n\nWhen mitosis goes wrong: uncontrolled cell division = cancer.\n\nMitosis is for growth, repair, and asexual reproduction. It's NOT for making sperm/eggs (that's meiosis).", "biology", 2),
    ("What is meiosis?", "Meiosis makes sex cells (sperm and egg) with HALF the chromosomes.\n\nMeiosis I (reduction division):\n1. Prophase I: Homologous chromosomes pair up and CROSS OVER (swap DNA)\n2. Metaphase I: Pairs line up at center\n3. Anaphase I: Pairs separate (not individual chromosomes)\n4. Telophase I: Two cells, each with 23 chromosomes (but still duplicated)\n\nMeiosis II (like mitosis):\n5. Prophase II-Metaphase II-Anaphase II-Telophase II\n6. Individual chromosomes split into chromatids\n\nResult: 4 cells, each with 23 chromosomes (haploid)\n\nKey differences from mitosis:\n- Mitosis: 1 division → 2 cells, 46 chromosomes each\n- Meiosis: 2 divisions → 4 cells, 23 chromosomes each\n- Meiosis creates genetic diversity through crossing over AND random assortment", "biology", 3),
    ("What is ATP?", "ATP (Adenosine Triphosphate) is the energy currency of the cell.\n\nStructure: adenine + ribose + three phosphate groups\n\nHow it works:\n- ATP → ADP + P + energy (when a phosphate bond breaks)\n- ADP + P + energy → ATP (when the bond reforms)\n\nThink of it like a rechargeable battery:\n- Charged: ATP (3 phosphates)\n- Discharged: ADP (2 phosphates)\n- Recharging: requires energy from food or sunlight\n\nWhere ATP is made:\n- Cellular respiration: ~36-38 ATP per glucose molecule\n- Photosynthesis: makes ATP in the light reactions\n\nYour body recycles its own weight in ATP every day. Each ATP molecule is used and recharged thousands of times daily.", "biology", 2),
    ("What is cellular respiration?", "Cellular respiration converts glucose into ATP (usable energy).\n\nC₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ~36 ATP\n\nThree stages:\n\n1. Glycolysis (in cytoplasm):\n   - Glucose → 2 pyruvate\n   - 2 ATP (net), 2 NADH\n   - No oxygen needed\n\n2. Krebs Cycle (in mitochondria):\n   - Pyruvate → CO₂\n   - 2 ATP, lots of NADH and FADH₂\n   - Oxygen needed\n\n3. Electron Transport Chain (inner mitochondrial membrane):\n   - NADH/FADH₂ donate electrons\n   - Oxygen is the final electron acceptor\n   - ~32-34 ATP\n   - This is where most energy is produced\n\nTotal: ~36-38 ATP per glucose\n\nWithout oxygen: only glycolysis runs → 2 ATP (anaerobic respiration / fermentation)", "biology", 3),
    ("What are the types of RNA?", "Three main types of RNA:\n\n1. mRNA (messenger RNA):\n   - Carries the genetic code from DNA to ribosomes\n   - Read in codons (3 bases = 1 amino acid)\n   - Short-lived — destroyed after being read\n\n2. tRNA (transfer RNA):\n   - Delivers amino acids to the ribosome\n   - Has an anticodon that matches the mRNA codon\n   - Cloverleaf shape with amino acid attached at one end\n   - Example: tRNA with anticodon UAC carries Methionine\n\n3. rRNA (ribosomal RNA):\n   - Forms the structure of ribosomes\n   - Catalyzes peptide bond formation (it's a ribozyme!)\n   - Most abundant RNA in the cell (~80%)\n\nBonus: snRNA (small nuclear) helps process mRNA in eukaryotes, and miRNA (micro) regulates gene expression.", "biology", 2),
    ("What is a mutation?", "A mutation is a change in the DNA sequence.\n\nTypes:\n\nPoint mutations (one base changed):\n- Substitution: A → G (one base swapped)\n  - Silent: No effect (codon still codes for same amino acid)\n  - Missense: Changes amino acid (sickle cell: GAG → GTG)\n  - Nonsense: Creates a stop codon (truncated protein)\n\nFrameshift mutations (shift reading frame):\n- Insertion: Extra base added\n- Deletion: Base removed\n  - Everything downstream is wrong! Usually catastrophic\n\nChromosomal mutations:\n- Deletion: Section of chromosome lost\n- Duplication: Section copied extra\n- Inversion: Section flipped around\n- Translocation: Section moved to different chromosome\n\nCauses: UV radiation, chemicals, errors during DNA replication, transposons\n\nMost mutations are neutral. Some are harmful. Very rarely, a mutation is beneficial — and that's the raw material for evolution.", "biology", 3),
    ("What is the difference between genotype and phenotype?", "Genotype: The genetic makeup (the alleles you carry)\nPhenotype: The observable traits (what you look like / how you function)\n\nExample with eye color:\n- Genotype: BB, Bb, or bb (the allele combination)\n- Phenotype: Brown eyes or blue eyes (what you see)\n\nBB → Brown eyes (homozygous dominant)\nBb → Brown eyes (heterozygous, B is dominant)\nbb → Blue eyes (homozygous recessive)\n\nKey points:\n- Same phenotype can come from different genotypes (BB and Bb both give brown eyes)\n- Genotype is not always visible in the phenotype\n- Environment affects phenotype too: identical twins with same genotype can look different due to diet, sun exposure, etc.\n- Penetrance: not everyone with the genotype shows the phenotype", "biology", 2),
    ("Explain the immune system simply", "Your immune system has two branches:\n\nInnate immunity (born with it, fast, non-specific):\n- Skin: physical barrier\n- Mucus and cilia: trap and sweep out pathogens\n- Inflammation: redness, heat, swelling (brings immune cells)\n- Phagocytes: white blood cells that eat invaders\n- Complement proteins: punch holes in bacteria\n- Responds within hours, same way every time\n\nAdaptive immunity (learned, slow, specific):\n- B cells: make antibodies that tag specific pathogens\n- T cells: killer T cells destroy infected cells, helper T cells coordinate\n- Memory cells: remember the pathogen for faster response next time\n- Responds in days, but highly targeted\n- Basis of vaccines: expose to harmless version → memory cells form → real infection fought off fast\n\nHow vaccines work: Show your immune system a 'mugshot' of the pathogen (dead, weakened, or piece of it) so it can prepare memory cells before the real threat arrives.", "biology", 3),
    ("What is genetic engineering / CRISPR?", "Genetic engineering: directly modifying an organism's DNA.\n\nTraditional methods:\n- Recombinant DNA: cut and paste genes between organisms (insulin from E. coli)\n- Gene therapy: insert healthy gene to replace defective one\n- GMOs: add genes for pest resistance, nutrition, etc.\n\nCRISPR-Cas9 (revolutionary, 2012):\n1. Guide RNA: a sequence that matches the target DNA\n2. Cas9 protein: molecular scissors that cut DNA at that spot\n3. Cell's repair machinery: inserts the new desired sequence\n\nWhy CRISPR is a game-changer:\n- Precise: targets exact location in the genome\n- Cheap: costs ~$75 per experiment vs thousands before\n- Fast: results in days, not months\n- Versatile: works in any organism\n\nApplications:\n- Disease: sickle cell correction, cancer immunotherapy\n- Agriculture: drought-resistant crops, disease-resistant livestock\n- Diagnostics: detecting viruses, cancer mutations\n- Controversial: designer babies, gene drives (modify entire species)", "biology", 4),
    ("What is the carbon cycle?", "The carbon cycle describes how carbon moves through Earth's systems.\n\nMain reservoirs:\n- Atmosphere: CO₂ (~0.04% but rising)\n- Oceans: dissolved CO₂, carbonates in shells\n- Land: plants, soil, fossil fuels\n- Rock: limestone, chalk\n\nCarbon flows:\n1. Photosynthesis: CO₂ → organic carbon (plants take it in)\n2. Respiration: organic carbon → CO₂ (all living things release it)\n3. Decomposition: dead organisms → CO₂ + soil carbon\n4. Combustion: burning fossil fuels/wood → CO₂\n5. Ocean absorption: CO₂ dissolves in water\n6. Weathering: rocks release/absorb carbon\n\nHuman impact: Burning fossil fuels releases carbon that was locked away for millions of years. This adds CO₂ to the atmosphere faster than natural processes can remove it.\n\nBefore industrial revolution: ~280 ppm CO₂\nNow: ~420 ppm CO₂\n\nThis extra CO₂ traps heat → climate change.", "biology", 3),
    ("What is the difference between DNA and RNA?", "DNA vs RNA:\n\nStructure:\n- DNA: Double-stranded helix, deoxyribose sugar\n- RNA: Single-stranded, ribose sugar\n\nBases:\n- DNA: A, T, G, C (Thymine)\n- RNA: A, U, G, C (Uracil replaces Thymine)\n\nLocation:\n- DNA: Nucleus (in eukaryotes)\n- RNA: Nucleus AND cytoplasm\n\nStability:\n- DNA: Very stable (the permanent storage)\n- RNA: Less stable (temporary working copies)\n\nTypes:\n- DNA: One type (the genome)\n- RNA: Multiple types (mRNA, tRNA, rRNA, miRNA, etc.)\n\nFunction:\n- DNA: Long-term storage of genetic information (the master blueprint)\n- RNA: Transfers and expresses genetic information (the working copy and machinery)\n\nAnalogy: DNA is the reference book in the library. RNA is the photocopy you take to your desk to work with.", "biology", 2),
    ("What is evolution?", "Evolution is the change in inherited traits of populations over generations.\n\nKey mechanisms:\n\n1. Natural selection: Traits that improve survival/reproduction become more common\n2. Genetic drift: Random changes in allele frequency (stronger in small populations)\n3. Gene flow: Migration between populations mixes genes\n4. Mutation: New genetic variation arises\n\nEvidence for evolution:\n- Fossil record: Shows gradual changes over time\n- Comparative anatomy: Homologous structures (your arm, whale flipper, bat wing share bone pattern)\n- Molecular: DNA sequences are more similar in closely related species\n- Embryology: Early embryos of many species look remarkably similar\n- Direct observation: Bacteria evolving antibiotic resistance, Darwin's finches\n\nCommon misconceptions:\n- Evolution has no goal or direction\n- 'Survival of the fittest' means best adapted, not strongest\n- Individuals don't evolve — populations do\n- Evolution doesn't 'start over' — it modifies existing structures", "biology", 3),
    ("What are the kingdoms of life?", "Historically, six kingdoms:\n\n1. Bacteria: Prokaryotic, single-celled, everywhere. Include beneficial and harmful species.\n\n2. Archaea: Prokaryotic, single-celled, often extreme environments (hot springs, salt lakes). Distinct from bacteria genetically.\n\n3. Protista: Eukaryotic, mostly single-celled. Amoebas, paramecia, algae. Grab bag of things that don't fit elsewhere.\n\n4. Fungi: Eukaryotic, heterotrophic (absorb nutrients). Mushrooms, yeasts, molds. Decomposers.\n\n5. Plantae: Eukaryotic, autotrophic (photosynthesis). Cell walls of cellulose. Multicellular.\n\n6. Animalia: Eukaryotic, heterotrophic (ingest food). No cell walls. Multicellular. That's us!\n\nModern classification (3 domains):\n- Bacteria\n- Archaea\n- Eukarya (includes protists, fungi, plants, animals)\n\nThis domain system is based on ribosomal RNA, which shows that archaea are actually more closely related to eukaryotes than to bacteria.", "biology", 2),

# ============================================================
# GEOMETRY & TRIG (40 more examples - was 11, target 50)
# ============================================================
    ("What is the perimeter of a rectangle with length 12 and width 5?", "P = 2(length + width)\nP = 2(12 + 5) = 2(17) = 34\n\nThe perimeter is 34 units.", "geometry", 1),
    ("Find the area of a trapezoid with bases 6 and 10 and height 4", "A = ½(b₁ + b₂) × h\nA = ½(6 + 10) × 4\nA = ½(16) × 4\nA = 8 × 4 = 32\n\nThe area is 32 square units.", "geometry", 2),
    ("What is the surface area of a sphere with radius 5?", "A = 4πr²\nA = 4π(25) = 100π ≈ 314.16\n\nThe surface area is 100π square units, about 314.", "geometry", 2),
    ("What is the volume of a sphere with radius 3?", "V = (4/3)πr³\nV = (4/3)π(27) = 36π ≈ 113.1\n\nThe volume is 36π cubic units, about 113.", "geometry", 2),
    ("A right triangle has a hypotenuse of 13 and one leg of 5. Find the other leg.", "Pythagorean theorem: a² + b² = c²\n5² + b² = 13²\n25 + b² = 169\nb² = 144\nb = 12\n\nThe other leg is 12. This is a 5-12-13 Pythagorean triple!", "geometry", 2),
    ("What is the distance between points (1, 3) and (4, 7)?", "Distance formula: d = √((x₂-x₁)² + (y₂-y₁)²)\n\nd = √((4-1)² + (7-3)²)\nd = √(3² + 4²)\nd = √(9 + 16)\nd = √25 = 5\n\nThe distance is 5 units.", "geometry", 2),
    ("What is the midpoint between (2, 4) and (8, 10)?", "Midpoint formula: M = ((x₁+x₂)/2, (y₁+y₂)/2)\n\nM = ((2+8)/2, (4+10)/2)\nM = (10/2, 14/2)\nM = (5, 7)\n\nThe midpoint is (5, 7).", "geometry", 1),
    ("What are the special right triangles?", "Two important ones to memorize:\n\n45-45-90 triangle:\n- Angles: 45°, 45°, 90°\n- Sides: 1, 1, √2\n- If legs = x, hypotenuse = x√2\n\n30-60-90 triangle:\n- Angles: 30°, 60°, 90°\n- Sides: 1, √3, 2\n- If short leg = x, long leg = x√3, hypotenuse = 2x\n\nPythagorean triples (integer sides):\n3-4-5 (and multiples: 6-8-10, 9-12-15...)\n5-12-13\n8-15-17\n7-24-25\n\nThese show up constantly on tests — memorize them!", "geometry", 2),
    ("What is the equation of a circle?", "Standard form: (x - h)² + (y - k)² = r²\n\nCenter at (h, k), radius r.\n\nExamples:\n- x² + y² = 25 → center (0,0), radius 5\n- (x - 3)² + (y + 2)² = 16 → center (3,-2), radius 4\n\nIf given expanded form: x² + y² + Dx + Ey + F = 0\nComplete the square to get back to standard form.\n\nExample: x² + y² - 6x + 4y - 12 = 0\n(x² - 6x + 9) + (y² + 4y + 4) = 12 + 9 + 4\n(x - 3)² + (y + 2)² = 25\nCenter (3, -2), radius 5", "geometry", 3),
    ("What is the law of sines?", "a/sin(A) = b/sin(B) = c/sin(C)\n\nUse when you know:\n- Two angles and a side (AAS or ASA)\n- Two sides and an angle opposite one of them (SSA — ambiguous case!)\n\nExample: In triangle ABC, A = 40°, B = 75°, a = 10. Find b.\nC = 180° - 40° - 75° = 65°\n\n10/sin(40°) = b/sin(75°)\nb = 10 × sin(75°)/sin(40°)\nb = 10 × 0.966/0.643\nb ≈ 15.02\n\nWarning — SSA ambiguous case: Given two sides and a non-included angle, there could be 0, 1, or 2 valid triangles. Always check!", "geometry", 3),
    ("What are radians?", "Radians are another way to measure angles, based on the arc length.\n\n1 radian = the angle where the arc length equals the radius.\n\nFull circle = 2π radians = 360°\nHalf circle = π radians = 180°\n\nConversions:\n- Degrees to radians: multiply by π/180\n- Radians to degrees: multiply by 180/π\n\nCommon values:\n0° = 0 rad\n30° = π/6\n45° = π/4\n60° = π/3\n90° = π/2\n180° = π rad\n270° = 3π/2\n360° = 2π rad\n\nWhy use radians?\n- Calculus formulas only work in radians\n- sin(x) ≈ x for small x in radians (but not degrees)\n- Arc length = rθ (in radians) — simple formula\n- Unit circle: angle in radians equals the arc length", "geometry", 3),
    ("Find the equation of a line passing through (2, 3) and (6, 11)", "Step 1: Find slope\nm = (y₂ - y₁)/(x₂ - x₁) = (11 - 3)/(6 - 2) = 8/4 = 2\n\nStep 2: Use point-slope form\ny - y₁ = m(x - x₁)\ny - 3 = 2(x - 2)\ny - 3 = 2x - 4\ny = 2x - 1\n\nOr in standard form: 2x - y = 1\n\nCheck: (2,3) → 2(2) - 1 = 3 ✓\n(6,11) → 2(6) - 1 = 11 ✓", "geometry", 2),
    ("What is the volume of a cone with radius 4 and height 9?", "V = (1/3)πr²h\nV = (1/3)π(16)(9)\nV = (1/3)π(144)\nV = 48π ≈ 150.8\n\nThe volume is 48π cubic units, about 151.\n\nNote: A cone's volume is exactly 1/3 of a cylinder with the same base and height.", "geometry", 2),
    ("What are similar triangles?", "Similar triangles have the same shape but different sizes.\n\nConditions for similarity:\n1. AA: Two angles match (third automatically matches too)\n2. SAS: Two sides proportional AND included angle matches\n3. SSS: All three sides proportional\n\nIf similar with scale factor k:\n- All sides are k times longer\n- All angles are the same\n- Area is k² times larger\n- Volume (if 3D) is k³ times larger\n\nExample: Triangle with sides 3-4-5 is similar to one with sides 6-8-10 (scale factor 2).\nArea of 6-8-10 = 4 × area of 3-4-5", "geometry", 3),

# ============================================================
# CS (45 more examples - was 5, target 50)
# ============================================================
    ("What is a variable in programming?", "A variable is a named container that stores a value in memory.\n\nThink of it like a labeled box:\n- name = \"Alice\" → a box labeled 'name' containing the string \"Alice\"\n- age = 25 → a box labeled 'age' containing the number 25\n\nKey concepts:\n- Declaration: creating the variable (some languages require this)\n- Assignment: giving it a value (x = 5)\n- Type: what kind of data it holds (number, string, boolean, etc.)\n- Scope: where in the code the variable is accessible\n\nStatic typing (Java, C++): type must be declared\nint age = 25;\n\nDynamic typing (Python, JavaScript): type is inferred\nage = 25\n\nVariables can be reassigned:\nx = 5\nx = 10  # x is now 10", "cs", 1),
    ("What is a loop?", "A loop repeats a block of code multiple times.\n\nFor loop (known number of times):\nfor i in range(5):\n    print(i)  # prints 0, 1, 2, 3, 4\n\nWhile loop (repeat while condition is true):\ncount = 0\nwhile count < 5:\n    print(count)\n    count += 1\n\nCommon patterns:\n- Counting: repeat N times\n- Accumulating: sum = 0; for each item: sum += item\n- Searching: loop until you find what you need\n- Processing: do something to every item in a collection\n\nDangers:\n- Infinite loop: condition never becomes false\n- Off-by-one: loop runs one too many or too few times\n- Modifying collection while iterating over it", "cs", 1),
    ("What is an array?", "An array is an ordered collection of items stored contiguously in memory.\n\nKey properties:\n- Indexed: access items by position (0-based in most languages)\n- Fixed size (in static arrays) or dynamic (in Python lists, JavaScript arrays)\n- Fast access: O(1) to read/write any element by index\n\nExample:\nfruits = [\"apple\", \"banana\", \"cherry\"]\nfruits[0] → \"apple\"\nfruits[1] → \"banana\"\nfruits[2] → \"cherry\"\n\nCommon operations:\n- Access by index: O(1)\n- Search for value: O(n)\n- Insert at end: O(1) amortized\n- Insert at beginning: O(n) — must shift all elements\n- Delete from middle: O(n) — must shift elements\n\nThis is why inserting at the beginning of a large array is slow!", "cs", 2),
    ("What is a linked list?", "A linked list stores data in nodes, where each node points to the next one.\n\nStructure:\n[Data|Next] → [Data|Next] → [Data|Next] → null\n\nvs Array:\nArray: [a][b][c][d] (contiguous memory)\nLinked List: [a]→[b]→[c]→[d] (scattered memory, linked by pointers)\n\nOperations:\n- Access by index: O(n) — must traverse from head\n- Insert at head: O(1) — just update pointer\n- Insert at tail: O(n) without tail pointer, O(1) with\n- Delete: O(n) to find, O(1) to remove (just redirect pointers)\n\nWhen to use linked list over array:\n- Frequent insertions/deletions at the beginning\n- Unknown size that changes frequently\n- Don't need random access\n\nWhen to use array over linked list:\n- Need fast access by index\n- Memory efficiency (no pointer overhead)\n- Cache locality matters (arrays are cache-friendly)", "cs", 3),
    ("What is a binary search tree?", "A BST is a tree where each node has at most 2 children:\n- Left child's value < parent's value\n- Right child's value > parent's value\n\nExample:\n      8\n     / \\\n    3   10\n   / \\    \\\n  1   6   14\n\nOperations (average case):\n- Search: O(log n) — at each node, go left or right\n- Insert: O(log n) — find the right spot, add it\n- Delete: O(log n) — three cases (leaf, one child, two children)\n\nWorst case (unbalanced): O(n) — degenerates into a linked list\n\nTraversal orders:\n- In-order (left, root, right): gives sorted output\n- Pre-order (root, left, right): copies the tree\n- Post-order (left, right, root): deletes the tree\n\nBalanced variants (AVL, Red-Black) guarantee O(log n) by self-balancing after insertions.", "cs", 3),
    ("What is sorting? Explain common algorithms", "Sorting = arranging items in order (ascending or descending).\n\nO(n²) algorithms (simple but slow for large data):\n\nBubble Sort: Swap adjacent items if out of order. Repeat until sorted.\n- Simple but very slow. O(n²) average and worst.\n\nSelection Sort: Find minimum, swap to front. Repeat for remaining.\n- Always O(n²), never better.\n\nInsertion Sort: Insert each item into its correct position.\n- O(n²) worst, but O(n) for nearly sorted data. Good for small arrays.\n\nO(n log n) algorithms (efficient):\n\nMerge Sort: Split in half, sort each half, merge.\n- Always O(n log n), stable, needs O(n) extra space.\n\nQuick Sort: Pick pivot, partition, recurse.\n- O(n log n) average, O(n²) worst, in-place, very fast in practice.\n\nHeap Sort: Build max heap, extract max repeatedly.\n- O(n log n) guaranteed, in-place, not stable.\n\nPractical choice: Most languages use Timsort (hybrid of merge + insertion) or a tuned quicksort.", "cs", 3),
    ("What is a stack and a queue?", "Stack: Last In, First Out (LIFO)\n- Like a stack of plates — you add and remove from the top\n- Push: add to top\n- Pop: remove from top\n- Peek: look at top without removing\n- All operations: O(1)\n\nUses: function call stack, undo/redo, expression evaluation, backtracking\n\nQueue: First In, First Out (FIFO)\n- Like a line at a store — first person in line is first served\n- Enqueue: add to back\n- Dequeue: remove from front\n- All operations: O(1)\n\nUses: task scheduling, BFS (breadth-first search), print queues, message queues\n\nComparison:\nStack: abc in → cba out (last one in, first one out)\nQueue: abc in → abc out (first one in, first one out)\n\nDeque (double-ended queue): can add/remove from both ends. Combines stack + queue.", "cs", 2),
    ("What is an API?", "API = Application Programming Interface\n\nA set of rules that allows different programs to communicate.\n\nAnalogy: A restaurant menu.\n- You (client) look at the menu (API documentation)\n- You order (make a request)\n- The kitchen (server) prepares your food\n- The waiter (API) delivers it (response)\n- You don't need to know how the kitchen works\n\nTypes:\n- REST API: Uses HTTP methods (GET, POST, PUT, DELETE) with URLs\n- GraphQL: Query exactly what you need, nothing more\n- WebSocket: Real-time two-way communication\n- Library API: Functions you call in code (like math.sqrt())\n\nREST example:\nGET /api/users → list all users\nGET /api/users/123 → get user 123\nPOST /api/users → create a new user\nDELETE /api/users/123 → delete user 123\n\nAPIs are how modern apps work — your weather app calls a weather API, your game calls a server API, etc.", "cs", 2),
    ("What is a database?", "A database is an organized collection of data, designed for efficient storage and retrieval.\n\nTwo main types:\n\nRelational (SQL):\n- Data in tables with rows and columns\n- Strict schema (defined structure)\n- Relationships between tables (foreign keys)\n- ACID transactions (reliable)\n- Examples: PostgreSQL, MySQL, SQLite\n\nQuery: SELECT name, age FROM users WHERE age > 18\n\nNoSQL (non-relational):\n- Flexible schema (documents, key-value, graph)\n- Better for unstructured or rapidly changing data\n- Often faster for simple lookups\n- Examples: MongoDB (documents), Redis (key-value), Neo4j (graph)\n\nQuery: db.users.find({age: {$gt: 18}})\n\nWhen to use SQL:\n- Data has clear relationships\n- Need complex queries and joins\n- Need strong consistency (banking, orders)\n\nWhen to use NoSQL:\n- Schema changes frequently\n- Need horizontal scaling\n- Working with documents or cache", "cs", 3),
    ("What is object-oriented programming?", "OOP organizes code around objects that combine data and behavior.\n\nFour pillars:\n\n1. Encapsulation: Bundle data + methods, hide internals\n   class Dog:\n       def __init__(self, name):\n           self._name = name  # private\n       def bark(self):\n           return f\"{self._name} says woof!\"\n\n2. Inheritance: Child classes inherit from parent\n   class GuideDog(Dog):  # Gets all Dog abilities + adds its own\n       def guide(self):\n           return \"Leading the way\"\n\n3. Polymorphism: Same interface, different behavior\n   class Cat:\n       def speak(self): return \"Meow\"\n   class Dog:\n       def speak(self): return \"Woof\"\n   # Same method name, different output\n\n4. Abstraction: Hide complexity, show essentials\n   You call car.start() without knowing the engine details\n\nBenefits: Code reuse, modularity, easier maintenance, models real-world entities\nTrade-offs: More code upfront, can be over-engineered, performance overhead", "cs", 3),
    ("What is recursion vs iteration?", "Both solve problems by repeating steps, but differently:\n\nRecursion: Function calls itself\n- Base case stops it\n- Elegant for: trees, divide-and-conquer, mathematical definitions\n- Uses call stack (can overflow for deep recursion)\n- Often slower (function call overhead)\n\ndef factorial(n):\n    if n == 0: return 1\n    return n * factorial(n-1)\n\nIteration: Uses loops (for, while)\n- Explicit stopping condition\n- Better for: simple repetition, linear traversal\n- No stack overflow risk\n- Usually faster (no function call overhead)\n\ndef factorial(n):\n    result = 1\n    for i in range(1, n+1):\n        result *= i\n    return result\n\nWhen recursion is better:\n- Tree traversals (binary tree DFS)\n- Problems naturally defined recursively (Fibonacci, fractals)\n- Divide and conquer (merge sort, quick sort)\n\nWhen iteration is better:\n- Simple counting or accumulation\n- Performance matters\n- Deep recursion could overflow stack\n\nAny recursion can be rewritten as iteration (and vice versa), but some problems are much more natural one way.", "cs", 2),
    ("What is a graph in computer science?", "A graph = nodes (vertices) connected by edges.\n\nTypes:\n- Undirected: edges go both ways (friendships, roads)\n- Directed: edges have direction (follows, one-way streets)\n- Weighted: edges have costs (distances, prices)\n- Unweighted: all edges are equal\n\nRepresentations:\n- Adjacency matrix: 2D array, 1 if edge exists, 0 if not. O(V²) space.\n- Adjacency list: each node stores list of neighbors. O(V+E) space. More common.\n\nKey algorithms:\n- BFS (Breadth-First Search): level by level. Finds shortest path in unweighted graphs. Uses a queue.\n- DFS (Depth-First Search): go deep first. Good for connectivity, cycles, topological sort. Uses a stack (or recursion).\n- Dijkstra's: shortest path in weighted graphs (no negative weights)\n- A*: Dijkstra's with a heuristic (used in GPS navigation, game AI)\n\nReal uses: social networks, maps/GPS, web crawling, recommendation systems, network routing", "cs", 3),
    ("What is version control / Git?", "Version control tracks changes to code over time.\n\nGit basics:\n- Repository (repo): project folder with full history\n- Commit: a snapshot of changes with a message\n- Branch: parallel version for new features\n- Merge: combine branches back together\n\nWorkflow:\n1. git init — create a repo\n2. git add file.py — stage changes\n3. git commit -m 'Add feature' — save snapshot\n4. git branch feature — create a branch\n5. git checkout feature — switch to it\n6. git merge feature — combine into main\n\nWhy it matters:\n- Time machine: revert to any previous version\n- Collaboration: multiple people work simultaneously\n- Branching: try things without breaking main code\n- Blame: see who changed what and when\n\nGitHub/GitLab: cloud hosting for Git repos + collaboration features (PRs, issues, CI/CD)\n\nConflicts: When two people edit the same line, Git can't auto-merge. You manually resolve, then commit.", "cs", 2),
    ("What is the difference between compiled and interpreted languages?", "Compiled:\n- Source code → compiler → machine code → run\n- Fast execution (already translated)\n- Errors caught before running\n- Examples: C, C++, Rust, Go\n\nInterpreted:\n- Source code → interpreter → run directly (line by line)\n- Slower execution (translated on the fly)\n- More flexible (dynamic typing, eval)\n- Examples: Python, JavaScript, Ruby\n\nHybrid (JIT — Just In Time):\n- Source code → bytecode → JIT compiler → machine code at runtime\n- Best of both: portability + speed\n- Examples: Java (JVM), C# (CLR), JavaScript (V8 engine)\n\nTrade-offs:\n- Compiled: faster, catches errors early, less portable\n- Interpreted: slower, more flexible, highly portable\n- JIT: good performance after warmup, portable bytecode\n\nIn practice, the distinction is blurry — Python has compiled bytecode (.pyc), and C can be interpreted with the right tool. The key difference is when translation to machine code happens.", "cs", 2),

# ============================================================
# MORE PHYSICS (20 examples - pad toward 50)
# ============================================================
    ("What is Ohm's Law?", "V = IR\n\nV = voltage (volts) — the 'push' on electrons\nI = current (amps) — the flow of electrons\nR = resistance (ohms) — how much the material resists flow\n\nAnalogy: Water in a pipe\n- Voltage = water pressure\n- Current = flow rate\n- Resistance = pipe narrowness\n\nExample: A 9V battery connected to a 300Ω resistor\nI = V/R = 9/300 = 0.03 A = 30 mA\n\nPower: P = IV = I²R = V²/R\nA 9V battery with 300Ω: P = 9²/300 = 0.27 W", "physics", 2),
    ("What is Coulomb's Law?", "F = kq₁q₂/r²\n\nThe force between two charges:\n- Like charges (both + or both -): repel (F is positive)\n- Unlike charges (+ and -): attract (F is negative)\n- k = 8.99 × 10⁹ N·m²/C²\n\nExample: Two 1μC charges 1m apart:\nF = (8.99×10⁹)(10⁻⁶)(10⁻⁶)/1² = 0.00899 N\n\nKey parallels with gravity:\n- Both are inverse square laws (1/r²)\n- Gravity always attracts; electric force can attract or repel\n- Gravity dominates at large scales (planets)\n- Electric force dominates at small scales (atoms)", "physics", 3),
    ("What is specific heat capacity?", "Specific heat = energy needed to raise 1 kg of a substance by 1°C.\n\nQ = mcΔT\nQ = heat energy (Joules)\nm = mass (kg)\nc = specific heat (J/(kg·°C))\nΔT = temperature change (°C)\n\nCommon specific heats:\n- Water: 4,186 J/(kg·°C) — very high!\n- Iron: 450 J/(kg·°C)\n- Aluminum: 900 J/(kg·°C)\n- Air: ~1,005 J/(kg·°C)\n\nWater's high specific heat is why:\n- Coastal cities have milder climates (ocean absorbs/releases heat slowly)\n- Sweating cools you (water absorbs heat from your skin)\n- Water takes long to boil\n\nExample: Heating 2 kg of water from 20°C to 100°C:\nQ = 2 × 4186 × 80 = 669,760 J ≈ 670 kJ", "physics", 3),
    ("What is the difference between speed and velocity?", "Speed = distance / time (scalar — just a number)\nVelocity = displacement / time (vector — number + direction)\n\nExample: You run 400m around a track in 60 seconds.\n- Average speed = 400/60 = 6.67 m/s\n- Average velocity = 0 m/s (you ended where you started!)\n\nKey differences:\n- Speed is always positive; velocity can be negative (opposite direction)\n- Speed measures total path length; velocity measures net displacement\n- Speed = |velocity| (speed is the magnitude of velocity)\n\nInstantaneous vs average:\n- Your speedometer shows instantaneous speed\n- Your GPS calculates average speed for the trip\n\nIn physics, velocity matters more because direction matters. A car going 60 mph north and 60 mph south have the same speed but very different velocities!", "physics", 1),
    ("What is terminal velocity?", "Terminal velocity is when a falling object stops accelerating — gravity equals air resistance.\n\nForces on a falling object:\n- Gravity (down): F_g = mg\n- Air resistance (up): F_drag = ½ρv²C_dA\n\nAt terminal velocity: mg = ½ρv²C_dA\nv_terminal = √(2mg / ρC_dA)\n\nTypical terminal velocities:\n- Skydiver (spread): ~55 m/s (120 mph)\n- Skydiver (head-down): ~90 m/s (200 mph)\n- Raindrop: ~9 m/s (20 mph)\n- Ant: ~2 m/s (survives any fall!)\n\nThe object accelerates until drag = weight, then falls at constant speed.\n\nHeavier or more streamlined objects have higher terminal velocities. That's why a feather falls slowly (low mass, high drag) and a bowling ball falls fast (high mass, low drag).", "physics", 3),

# ============================================================
# MORE CHEMISTRY (15 examples - pad toward 40)
# ============================================================
    ("What is a mole?", "A mole is a counting unit, like 'dozen' means 12.\n\n1 mole = 6.022 × 10²³ particles (Avogadro's number)\n\nWhy this number? Because 6.022 × 10²³ atoms of carbon-12 weigh exactly 12 grams.\n\nMolar mass = mass of 1 mole of a substance (g/mol)\n- H: 1.008 g/mol\n- C: 12.01 g/mol\n- O: 16.00 g/mol\n- H₂O: 18.02 g/mol (2×1.008 + 16.00)\n\nConversions:\n- Moles to particles: multiply by 6.022 × 10²³\n- Grams to moles: divide by molar mass\n- Moles to grams: multiply by molar mass\n\nExample: How many molecules in 36g of H₂O?\n36g ÷ 18.02 g/mol = 2.0 mol\n2.0 × 6.022 × 10²³ = 1.2 × 10²⁴ molecules", "chemistry", 2),
    ("What are isotopes?", "Isotopes are atoms of the same element with different numbers of neutrons.\n\nSame protons (same element), different mass.\n\nExamples:\n- Carbon-12: 6 protons, 6 neutrons (most common, ~99%)\n- Carbon-13: 6 protons, 7 neutrons (~1%)\n- Carbon-14: 6 protons, 8 neutrons (radioactive, trace)\n\nAll are carbon — they behave the same chemically. Only the mass differs.\n\nWhy isotopes matter:\n- Carbon-14 dating: C-14 decays predictably, used to date organic material up to ~50,000 years\n- Medical imaging: I-131 for thyroid, Tc-99m for bone scans\n- Nuclear energy: U-235 is fissile (can sustain chain reactions), U-238 is not\n- Atomic mass on periodic table: weighted average of all isotopes", "chemistry", 2),
    ("What is a covalent bond?", "A covalent bond forms when two atoms share electrons.\n\nHappens between nonmetals that want to gain electrons.\n\nTypes:\n- Single bond: 1 pair shared (H-H, H-Cl)\n- Double bond: 2 pairs shared (O=O, C=O)\n- Triple bond: 3 pairs shared (N≡N)\n\nPolar covalent: Electrons shared unequally (one atom pulls harder)\n- H₂O: Oxygen pulls electrons more than hydrogen → partial charges\n- This creates a dipole (positive end and negative end)\n\nNonpolar covalent: Electrons shared equally\n- H₂, O₂, N₂, CH₄ — symmetric or same atoms\n\nElectronegativity difference determines bond type:\n- ΔEN < 0.4: nonpolar covalent\n- 0.4 < ΔEN < 1.7: polar covalent\n- ΔEN > 1.7: ionic (electron transfer, not sharing)", "chemistry", 2),
    ("What is solubility?", "Solubility = how much solute can dissolve in a solvent at a given temperature.\n\n'Like dissolves like':\n- Polar solvents dissolve polar/ionic solutes (water dissolves salt, sugar)\n- Nonpolar solvents dissolve nonpolar solutes (oil dissolves grease, wax)\n- Oil and water don't mix because oil is nonpolar, water is polar\n\nFactors affecting solubility:\n- Temperature: Most solids dissolve better in hot water; gases dissolve better in cold\n- Pressure: Henry's Law — gas solubility ∝ pressure (soda is carbonated under pressure)\n- Surface area: Powdered solute dissolves faster than chunks (more contact)\n- Stirring: Speeds up dissolving but doesn't change maximum solubility\n\nUnits: g solute per 100 g solvent at a specific temperature\n\nSaturation:\n- Unsaturated: can dissolve more\n- Saturated: at maximum (any extra won't dissolve)\n- Supersaturated: holds more than normal (unstable — crystallizes if disturbed)", "chemistry", 2),

# ============================================================
# MORE ALGEBRA (20 examples - pad toward 50)
# ============================================================
    ("What is a function?", "A function maps each input to exactly one output.\n\nf(x) = 2x + 3 means: put in x, get out 2x + 3\n\nf(4) = 2(4) + 3 = 11\nf(0) = 3\nf(-1) = 1\n\nKey concepts:\n- Domain: all valid inputs (x values)\n- Range: all possible outputs (y values)\n- One input → exactly one output (not zero, not two)\n\nVertical line test: If a vertical line hits the graph more than once, it's NOT a function.\n\nCommon functions:\n- Linear: f(x) = mx + b\n- Quadratic: f(x) = ax² + bx + c\n- Exponential: f(x) = aˣ\n- Logarithmic: f(x) = log_a(x)", "algebra", 1),
    ("What is slope?", "Slope = how steep a line is = rise/run = change in y / change in x\n\nm = (y₂ - y₁) / (x₂ - x₁)\n\nTypes:\n- Positive slope: line goes up-right (/)\n- Negative slope: line goes down-right (\\)\n- Zero slope: horizontal line (—)\n- Undefined slope: vertical line (|)\n\nExamples:\n- Slope 2: for every 1 right, go up 2 (steep uphill)\n- Slope -1/3: for every 3 right, go down 1 (gentle downhill)\n- Slope 0: flat, no rise\n\nIn y = mx + b:\n- m is the slope\n- b is the y-intercept (where the line crosses the y-axis)", "algebra", 1),
    ("What is a logarithm?", "log_b(x) = the power you raise b to, to get x.\n\nlog₁₀(100) = 2 because 10² = 100\nlog₂(8) = 3 because 2³ = 8\nln(x) = logₑ(x) where e ≈ 2.718 (natural log)\n\nKey properties:\n- log(ab) = log(a) + log(b)\n- log(a/b) = log(a) - log(b)\n- log(aⁿ) = n·log(a)\n- log_b(b) = 1\n- log_b(1) = 0\n\nLogarithms and exponentials are inverses:\n- If y = bˣ, then x = log_b(y)\n- log and exponent 'undo' each other\n\nCommon uses:\n- pH = -log[H⁺] (chemistry)\n- Decibels = 10·log(intensity) (sound)\n- Richter scale = log(earthquake energy) (geology)\n- Algorithm complexity: O(log n) (computer science)", "algebra", 3),
    ("Solve the inequality 3x - 7 > 2x + 5", "3x - 7 > 2x + 5\n\nSubtract 2x from both sides:\nx - 7 > 5\n\nAdd 7:\nx > 12\n\nCheck with x = 13: 3(13) - 7 = 32, 2(13) + 5 = 31, 32 > 31 ✓\nCheck with x = 12: 3(12) - 7 = 29, 2(12) + 5 = 29, 29 > 29 ✗\n\nImportant: When multiplying/dividing by a negative number, flip the inequality!\n-2x > 6 → x < -3 (not x > -3)", "algebra", 2),
    ("What is a polynomial?", "A polynomial is a sum of terms with variables raised to non-negative integer powers.\n\nGeneral form: aₙxⁿ + aₙ₋₁xⁿ⁻¹ + ... + a₁x + a₀\n\nExamples:\n- 3x² + 2x - 1 (quadratic, degree 2)\n- x⁵ - 4x³ + 7 (degree 5)\n- 7 (degree 0, constant)\n- 4x (degree 1, linear)\n\nNOT polynomials:\n- 1/x = x⁻¹ (negative exponent)\n- √x = x^(1/2) (fractional exponent)\n- 2ˣ (variable in exponent)\n\nDegree = highest power of x\nLeading coefficient = coefficient of the highest power\n\nOperations:\n- Add/subtract: combine like terms\n- Multiply: distribute (FOIL for binomials)\n- Divide: long division or synthetic division\n- Factor: find roots, use grouping, special patterns", "algebra", 2),

# ============================================================
# MORE CALCULUS (15 examples - pad toward 45)
# ============================================================
    ("What is a limit?", "A limit describes what a function approaches as x gets close to a value.\n\nlim(x→2) x² = 4\nAs x gets closer and closer to 2, x² gets closer and closer to 4.\n\nNotation: lim(x→a) f(x) = L means 'f(x) approaches L as x approaches a'\n\nImportant cases:\n- Direct substitution works: lim(x→3) (x+1) = 4\n- 0/0 form: need algebra (factor, rationalize, etc.)\n  lim(x→2) (x²-4)/(x-2) = lim(x→2) (x+2)(x-2)/(x-2) = 4\n- One-sided limits: lim(x→a⁺) from right, lim(x→a⁻) from left\n- Limit doesn't exist if left and right limits differ\n\nLimits are the foundation of calculus:\n- Derivative = limit of difference quotient\n- Integral = limit of Riemann sums\n- Continuity = limit equals function value", "calculus", 2),
    ("What is the Fundamental Theorem of Calculus?", "The FTC connects derivatives and integrals — they're inverses!\n\nPart 1: If F(x) = ∫ₐˣ f(t)dt, then F'(x) = f(x)\n(The derivative of the integral gives back the original function)\n\nPart 2: ∫ₐᵇ f(x)dx = F(b) - F(a)\nwhere F is any antiderivative of f\n(Evaluate the antiderivative at the bounds and subtract)\n\nWhy this is profound:\n- Derivatives measure instantaneous rate of change\n- Integrals measure total accumulation\n- They're opposite operations, like addition/subtraction\n\nExample: ∫₀² 3x² dx\nAntiderivative: x³\n= F(2) - F(0) = 8 - 0 = 8\n\nWithout FTC, you'd need to compute this as an infinite sum of rectangles. The FTC lets you just find an antiderivative and plug in bounds!", "calculus", 3),
    ("What is the Mean Value Theorem?", "If f is continuous on [a,b] and differentiable on (a,b), then there exists at least one point c in (a,b) where:\n\nf'(c) = [f(b) - f(a)] / (b - a)\n\nTranslation: There's at least one point where the instantaneous rate of change equals the average rate of change.\n\nExample: You drive 120 miles in 2 hours. Average speed = 60 mph.\nBy MVT, at some point during the trip, your speedometer read exactly 60 mph.\n\nEven if you sped up and slowed down, you MUST have hit 60 mph at least once.\n\nVisually: If you draw a secant line between (a, f(a)) and (b, f(b)), there's at least one point where the tangent line is parallel to it.\n\nPrerequisites: The function MUST be continuous and differentiable. A corner or jump disqualifies it.", "calculus", 4),
    ("What is the second derivative test?", "Use f''(x) to classify critical points:\n\nIf f'(c) = 0 and:\n- f''(c) > 0 → local minimum (curve bends up, like a cup)\n- f''(c) < 0 → local maximum (curve bends down, like a cap)\n- f''(c) = 0 → inconclusive (could be inflection point, min, or max)\n\nExample: f(x) = x³ - 3x\nf'(x) = 3x² - 3 = 0 → x = ±1\nf''(x) = 6x\n\nAt x = 1: f''(1) = 6 > 0 → local minimum ✓\nAt x = -1: f''(-1) = -6 < 0 → local maximum ✓\n\nWhen the second derivative test fails (f'' = 0), use the first derivative test instead: check if f' changes sign around the critical point.", "calculus", 3),

# ============================================================
# STATISTICS (20 examples - new topic)
# ============================================================
    ("What is the mean, median, and mode?", "Three ways to measure the center of a data set:\n\nMean (average): Sum of all values / count\nData: 2, 4, 4, 6, 9\nMean = (2+4+4+6+9)/5 = 25/5 = 5\n\nMedian: Middle value when sorted\nData: 2, 4, 4, 6, 9 → Median = 4\nFor even count: average the two middle values\nData: 2, 4, 6, 9 → Median = (4+6)/2 = 5\n\nMode: Most frequent value\nData: 2, 4, 4, 6, 9 → Mode = 4 (appears twice)\nCan have multiple modes or no mode.\n\nWhen to use each:\n- Mean: when data is roughly symmetric, no extreme outliers\n- Median: when data has outliers (income, housing prices)\n- Mode: for categorical data (favorite color, most common answer)\n\nOutlier example: Salaries 30K, 35K, 40K, 42K, 1M\nMean = 229.4K (misleading!)\nMedian = 40K (much better representation)", "statistics", 1),
    ("What is standard deviation?", "Standard deviation measures how spread out data is from the mean.\n\nLow SD: data points cluster close to the mean\nHigh SD: data points spread far from the mean\n\nFormula: σ = √(Σ(xᵢ - μ)² / N)\n\nSteps:\n1. Find the mean (μ)\n2. Subtract mean from each value: (xᵢ - μ)\n3. Square each difference\n4. Average the squared differences (variance)\n5. Take the square root (standard deviation)\n\nExample: Data = 2, 4, 4, 4, 5, 5, 7, 9\nMean = 5\nDifferences: -3, -1, -1, -1, 0, 0, 2, 4\nSquared: 9, 1, 1, 1, 0, 0, 4, 16\nVariance = (9+1+1+1+0+0+4+16)/8 = 4\nSD = √4 = 2\n\nThe 68-95-99.7 rule (normal distribution):\n- 68% of data within 1 SD of mean\n- 95% within 2 SD\n- 99.7% within 3 SD", "statistics", 2),
    ("What is a normal distribution?", "The bell curve — the most important distribution in statistics.\n\nProperties:\n- Symmetric around the mean (μ)\n- Mean = Median = Mode\n- Shape determined by μ (center) and σ (spread)\n- Total area under curve = 1\n\nThe 68-95-99.7 rule:\n- 68% of data: μ ± 1σ\n- 95% of data: μ ± 2σ\n- 99.7% of data: μ ± 3σ\n\nExample: SAT scores, μ = 1000, σ = 200\n- 68% score between 800-1200\n- 95% score between 600-1400\n- 99.7% score between 400-1600\n\nWhy it's everywhere:\n- Central Limit Theorem: means of large samples are approximately normal, regardless of the original distribution\n- Many natural phenomena are approximately normal (heights, measurement errors, test scores)\n- Makes statistical inference possible", "statistics", 2),
    ("What is a p-value?", "A p-value is the probability of getting results at least as extreme as observed, assuming the null hypothesis is true.\n\nNull hypothesis (H₀): 'There is no effect / no difference'\nAlternative hypothesis (H₁): 'There IS an effect / difference'\n\nIf p-value is small (typically < 0.05):\n- The observed data is unlikely under H₀\n- We reject H₀ and conclude there's evidence for an effect\n- NOT proof that H₁ is true — just evidence against H₀\n\nIf p-value is large (≥ 0.05):\n- The data is plausible under H₀\n- We fail to reject H₀\n- This does NOT prove H₀ is true — we just don't have enough evidence\n\nCommon mistakes:\n- p < 0.05 does NOT mean 95% chance the effect is real\n- p ≥ 0.05 does NOT mean there's no effect\n- P-hacking: running many tests and only reporting significant ones\n- Sample size matters — large samples can make tiny effects 'significant'", "statistics", 3),
    ("What is correlation vs causation?", "Correlation: Two variables move together (statistical relationship)\nCausation: One variable directly causes the other\n\n'Correlation does not imply causation' — the most important rule in statistics.\n\nWhy correlations happen without causation:\n1. Coincidence: Ice cream sales and shark attacks both peak in summer\n2. Confounding variable: Heat causes both ice cream sales AND swimming (which leads to shark attacks)\n3. Reverse causation: Does stress cause insomnia, or does insomnia cause stress?\n4. Third variable: Both are effects of a common cause\n\nHow to establish causation:\n- Randomized controlled trials (gold standard)\n- Controlling for confounders\n- Temporal precedence (cause must come before effect)\n- Mechanism (explain HOW A causes B)\n- Dose-response (more A → more B)\n\nExample: People who drink wine live longer. Is it the wine? Probably not — wine drinkers tend to be wealthier, have better healthcare, and healthier diets. The correlation is real but the causation is questionable.", "statistics", 2),
    ("What is a confidence interval?", "A confidence interval gives a range of plausible values for a population parameter.\n\n95% CI: If we repeated the study 100 times, about 95 of those intervals would contain the true value.\n\nFormula (for mean): x̄ ± z × (σ/√n)\n- x̄ = sample mean\n- z = z-score (1.96 for 95% CI)\n- σ = standard deviation\n- n = sample size\n\nExample:\nSample mean = 72, σ = 10, n = 100\n95% CI = 72 ± 1.96 × (10/√100)\n= 72 ± 1.96 × 1\n= 72 ± 1.96\n= (70.04, 73.96)\n\nInterpretation: We are 95% confident the true population mean is between 70.04 and 73.96.\n\nNOT: There's a 95% probability the true mean is in this interval. The true mean is fixed — it's either in the interval or it isn't.\n\nWider interval = more confident but less precise\nLarger sample = narrower interval (more precise)", "statistics", 3),

# ============================================================
# LINEAR ALGEBRA (10 examples - new topic)
# ============================================================
    ("What is a matrix?", "A matrix is a rectangular array of numbers organized in rows and columns.\n\nExample: A 2×3 matrix\n[1  2  3]\n[4  5  6]\n\n2 rows, 3 columns → dimensions are 2×3\n\nElement aᵢⱼ = element in row i, column j\na₁₂ = 2 (row 1, column 2)\na₂₃ = 6 (row 2, column 3)\n\nBasic operations:\n- Addition: add corresponding elements (same dimensions)\n- Scalar multiplication: multiply every element by a number\n- Matrix multiplication: row × column (inner dimensions must match)\n\nUses:\n- Computer graphics (transformations, rotations)\n- Machine learning (data representation, neural networks)\n- Systems of equations (Ax = b)\n- Quantum mechanics (operators)", "linear_algebra", 2),
    ("What is a vector?", "A vector has both magnitude and direction.\n\nIn 2D: v = (3, 4) — 3 units right, 4 units up\nIn 3D: v = (1, 2, 3)\n\nMagnitude: |v| = √(3² + 4²) = 5\n\nKey operations:\n- Addition: (1,2) + (3,4) = (4,6) (tip-to-tail)\n- Scalar multiplication: 2 × (1,2) = (2,4) (stretches/shrinks)\n- Dot product: (1,2) · (3,4) = 1×3 + 2×4 = 11 (measures alignment)\n- Cross product (3D only): gives a perpendicular vector\n\nDot product tells you alignment:\n- Positive: vectors point roughly same direction\n- Zero: perpendicular\n- Negative: opposite directions\n\nUnit vector: magnitude = 1, represents direction only\nNormalize: v̂ = v / |v| = (3/5, 4/5)", "linear_algebra", 2),

# ============================================================
# PROBABILITY (10 examples - new topic)
# ============================================================
    ("What is probability?", "Probability measures how likely an event is to occur.\n\nP(event) = favorable outcomes / total outcomes\n\nBasic rules:\n- P ranges from 0 (impossible) to 1 (certain)\n- P(A or B) = P(A) + P(B) - P(A and B)\n- P(not A) = 1 - P(A)\n- Independent events: P(A and B) = P(A) × P(B)\n\nExample: Rolling a die\nP(even) = 3/6 = 1/2 (2, 4, or 6)\nP(greater than 4) = 2/6 = 1/3 (5 or 6)\nP(even AND > 4) = 1/6 (only 6)\n\nTwo coins:\nP(both heads) = 1/2 × 1/2 = 1/4\nP(at least one head) = 1 - P(both tails) = 1 - 1/4 = 3/4", "probability", 1),
    ("What is conditional probability?", "Conditional probability: P(A|B) = probability of A given that B has already occurred.\n\nFormula: P(A|B) = P(A and B) / P(B)\n\nExample: A bag has 3 red and 5 blue marbles.\nP(red on 2nd draw | blue on 1st draw)\nAfter removing 1 blue: 3 red, 4 blue left\n= 3/7\n\nThis differs from P(red on 2nd draw) without knowing the first = 3/8\n\nBayes' Theorem (flipping the condition):\nP(A|B) = P(B|A) × P(A) / P(B)\n\nClassic example: Disease test\n- 1% of population has disease (P(D) = 0.01)\n- Test is 99% accurate (P(+|D) = 0.99, P(-|no D) = 0.99)\n- You test positive. P(D|+) = ?\n\nP(D|+) = 0.99 × 0.01 / (0.99 × 0.01 + 0.01 × 0.99)\n= 0.0099 / 0.0198 = 50%\n\nEven with a 99% accurate test, a positive result only means 50% chance of disease when the disease is rare!", "probability", 3),
    ("What is the binomial distribution?", "The binomial distribution models the number of successes in n independent trials, each with probability p of success.\n\nRequirements:\n- Fixed number of trials (n)\n- Each trial has two outcomes (success/failure)\n- Same probability p each trial\n- Trials are independent\n\nP(k successes) = C(n,k) × pᵏ × (1-p)ⁿ⁻ᵏ\n\nwhere C(n,k) = n! / (k!(n-k)!) is the binomial coefficient\n\nExample: 5 coin flips, probability of exactly 3 heads\nn = 5, p = 0.5, k = 3\nP(3) = C(5,3) × 0.5³ × 0.5² = 10 × 0.03125 = 0.3125\n\nMean = np = 5 × 0.5 = 2.5\nStandard deviation = √(np(1-p)) = √(1.25) ≈ 1.12\n\nReal examples: Pass/fail rates, conversion rates, quality control defect counts", "probability", 3),
]

if __name__ == "__main__":
    # This will be imported by generate_training_data.py
    print(f"Supplementary dataset has {len(SUPPLEMENT)} examples")
