"""
EduGemma - Supplementary Training Data Volume 3
Additional ~250 examples to reach 500+ target
Focus: statistics, probability, linear algebra, more depth in all topics
"""
SUPPLEMENT2 = [

# ============================================================
# STATISTICS (20 more - target 25)
# ============================================================
    ("What is the difference between population and sample?", "Population: The entire group you want to learn about.\nSample: A subset of the population that you actually study.\n\nExamples:\n- Population: All students at a university (50,000)\n- Sample: 500 students surveyed\n\n- Population: All light bulbs produced by a factory\n- Sample: 100 bulbs tested for lifespan\n\nWhy sample? Studying the whole population is often:\n- Too expensive\n- Too time-consuming\n- Impossible (e.g., all fish in the ocean)\n- Destructive (e.g., testing every bullet would use them all)\n\nKey distinction:\n- Population parameters: μ (mean), σ (SD) — fixed but usually unknown\n- Sample statistics: x̄ (mean), s (SD) — calculated from data, vary sample to sample\n\nGood samples are:\n- Random: every member has equal chance\n- Representative: mirrors the population's characteristics\n- Large enough: reduces sampling error\n\nBad samples lead to bias: surveying only online users misses non-internet users.", "statistics", 1),
    ("What is the difference between type I and type II errors?", "In hypothesis testing:\n\nType I Error (False Positive): Rejecting H₀ when H₀ is true\n- 'Convicting an innocent person'\n- Probability = α (significance level, usually 0.05)\n- You found an effect that doesn't actually exist\n\nType II Error (False Negative): Failing to reject H₀ when H₀ is false\n- 'Letting a guilty person go free'\n- Probability = β\n- You missed a real effect\n\nPower = 1 - β: probability of correctly detecting a real effect\n\nTrade-off: Decreasing one error increases the other (for fixed sample size)\n- Lower α → fewer Type I errors → more Type II errors\n- Higher α → fewer Type II errors → more Type I errors\n\nThe only way to reduce both: increase sample size\n\nReal examples:\n- Type I: Cancer screening says you have cancer when you don't (unnecessary stress/treatment)\n- Type II: Cancer screening misses real cancer (delayed treatment)\n\nWhich is worse depends on context. Medical tests often prioritize minimizing Type II (don't miss disease).", "statistics", 3),
    ("What is standard error?", "Standard Error (SE) measures how much a sample statistic varies from sample to sample.\n\nSE of the mean: SE = σ/√n\n\n- σ = population standard deviation\n- n = sample size\n\nIf σ is unknown (usually), use: SE = s/√n (sample SD)\n\nKey insight:\n- Larger sample → smaller SE → more precise estimate\n- SE decreases as √n, so doubling n only reduces SE by √2 ≈ 1.41\n\nExample:\nHeights: μ = 170cm, σ = 10cm\n- n = 25: SE = 10/5 = 2.0cm\n- n = 100: SE = 10/10 = 1.0cm\n- n = 400: SE = 10/20 = 0.5cm\n\nSE vs SD:\n- SD: spread of individual data points\n- SE: spread of sample means (how much x̄ varies)\n\nSE is what goes into confidence intervals:\n95% CI = x̄ ± 1.96 × SE", "statistics", 2),
    ("What is a hypothesis test?", "A structured way to make decisions using data.\n\nSteps:\n1. State hypotheses:\n   H₀ (null): No effect, no difference (the boring default)\n   H₁ (alternative): There IS an effect or difference\n\n2. Choose significance level α (usually 0.05)\n\n3. Calculate test statistic from data\n\n4. Find p-value\n\n5. Decision:\n   - p < α → Reject H₀ (statistically significant)\n   - p ≥ α → Fail to reject H₀ (not significant)\n\nCommon tests:\n- Z-test: comparing a mean to a known value (large sample)\n- T-test: comparing means (small sample, unknown σ)\n- Chi-square: testing relationships between categories\n- ANOVA: comparing 3+ group means\n\nExample: Is a coin fair?\nH₀: p = 0.5, H₁: p ≠ 0.5\nFlip 100 times, get 62 heads.\np-value = P(≥62 heads | fair coin) ≈ 0.012\nSince 0.012 < 0.05, reject H₀. The coin might be biased.", "statistics", 2),
    ("What is the law of large numbers?", "As sample size increases, the sample mean converges to the population mean.\n\nFormally: lim(n→∞) P(|x̄ - μ| > ε) = 0 for any ε > 0\n\nTranslation: Flip a fair coin more times → proportion of heads gets closer to 0.5\n\nExamples:\n- 10 flips: might get 7 heads (70%)\n- 100 flips: might get 55 heads (55%)\n- 1000 flips: likely near 505 heads (50.5%)\n- 1,000,000 flips: very close to 50%\n\nThis is why:\n- Casinos always win in the long run (their edge is small but guaranteed by LLN)\n- Polls with larger samples are more accurate\n- Insurance companies can predict claims precisely with enough policyholders\n\nCommon mistake: LLN does NOT say you're 'due' for heads after a streak of tails (that's the Gambler's Fallacy). Each flip is still 50/50. The convergence happens in the proportion, not by compensating for past results.", "statistics", 2),
    ("What is regression?", "Regression models the relationship between variables.\n\nSimple linear regression: y = mx + b\n- y = dependent variable (what we predict)\n- x = independent variable (what we use to predict)\n- m = slope (change in y per unit change in x)\n- b = intercept (y when x = 0)\n\nThe line of best fit minimizes the sum of squared errors (least squares).\n\nR² (coefficient of determination):\n- Ranges from 0 to 1\n- How much of the variation in y is explained by x\n- R² = 0.85 means 85% of y's variation is explained by x\n\nMultiple regression: y = b₀ + b₁x₁ + b₂x₂ + ...\n- Uses multiple predictors\n- Each coefficient shows the effect of that variable, holding others constant\n\nImportant warnings:\n- Correlation ≠ causation (regression shows association, not cause)\n- Extrapolation beyond data range is risky\n- Outliers can heavily influence the regression line\n- Check residuals for patterns (violates assumptions)", "statistics", 3),
    ("What is a z-score?", "A z-score tells you how many standard deviations a value is from the mean.\n\nz = (x - μ) / σ\n\nExample: Test score of 85, mean = 75, SD = 5\nz = (85 - 75) / 5 = 2\nYou scored 2 standard deviations above the mean.\n\nWhat z-scores mean:\n- z = 0: exactly average\n- z = 1: above 84.1% of people\n- z = -1: below 84.1% of people (above only 15.9%)\n- z = 2: above 97.7% of people\n- z = -2: below 97.7% (above only 2.3%)\n\nUses:\n- Comparing scores from different tests (SAT vs ACT)\n- Finding percentiles (what percentage scored below you)\n- Identifying outliers (|z| > 2 or 3 is unusual)\n- Calculating probabilities with the normal distribution\n\nConverting between different scales:\nSAT: μ=1000, σ=200, your score=1200 → z=1\nACT: μ=21, σ=5, equivalent ACT=21+1(5)=26\nBoth are 1 SD above average!", "statistics", 1),

# ============================================================
# PROBABILITY (15 more - target 18)
# ============================================================
    ("What is the multiplication rule for probability?", "For events A and B:\n\nIf independent: P(A and B) = P(A) × P(B)\nIf dependent: P(A and B) = P(A) × P(B|A)\n\nIndependent examples:\n- Two coin flips: P(both heads) = 0.5 × 0.5 = 0.25\n- Two dice: P(both 6) = (1/6) × (1/6) = 1/36\n\nDependent examples:\n- Drawing cards without replacement:\n  P(2 aces) = (4/52) × (3/51) = 12/2652 ≈ 0.0045\n\n  First ace: 4/52 (4 aces in 52 cards)\n  Second ace: 3/51 (3 aces left in 51 cards)\n\nCommon mistakes:\n- 'At least one' problems: use 1 - P(none)\n  P(at least one 6 in 3 dice) = 1 - P(no 6)³ = 1 - (5/6)³ ≈ 0.421\n- Don't assume independence without justification\n- Drawing without replacement makes events dependent!", "probability", 2),
    ("What is the addition rule for probability?", "P(A or B) = P(A) + P(B) - P(A and B)\n\nThe subtraction avoids double-counting the overlap.\n\nIf A and B are mutually exclusive (can't both happen):\nP(A or B) = P(A) + P(B)\n\nExample: Drawing a card\nP(heart or face card) = ?\nP(heart) = 13/52\nP(face card) = 12/52\nP(heart AND face) = 3/52 (J♥, Q♥, K♥)\n\nP(heart or face) = 13/52 + 12/52 - 3/52 = 22/52 ≈ 0.423\n\nWithout subtracting the overlap, you'd count the 3 heart face cards twice.\n\nMutually exclusive example:\nP(rolling 2 or 3 on a die)\n= P(2) + P(3) = 1/6 + 1/6 = 1/3\n(They can't both happen, so no overlap to subtract)", "probability", 1),
    ("What is expected value?", "Expected value (EV) = the average outcome if you repeated an experiment infinitely many times.\n\nEV = Σ(xᵢ × P(xᵢ))\nSum of: each outcome × its probability\n\nExample: Lottery ticket costs $2\n- 1% chance to win $100\n- 99% chance to win $0\n\nEV = 0.01 × 100 + 0.99 × 0 = $1\nNet EV = $1 - $2 (cost) = -$1\n\nOn average, you lose $1 per ticket. Don't buy it!\n\nExample: Fair coin flip, win $1 for heads, lose $1 for tails\nEV = 0.5 × 1 + 0.5 × (-1) = 0\nFair game — EV is zero.\n\nExample: Roulette bet on red\n18 red, 18 black, 2 green out of 38\nEV = (18/38) × 1 + (20/38) × (-1) = -2/38 ≈ -$0.053\nEvery $1 bet, you lose about 5 cents on average. The house always wins.\n\nPositive EV = good bet in the long run\nNegative EV = bad bet in the long run\nZero EV = fair game", "probability", 2),
    ("What are permutations and combinations?", "Both count ways to choose items, but order matters differently.\n\nPermutations: Order matters\nP(n,r) = n! / (n-r)!\n'How many ways to arrange r items from n?'\n\nExample: 8 runners, how many ways to award gold, silver, bronze?\nP(8,3) = 8!/(8-3)! = 8×7×6 = 336\n\nCombinations: Order doesn't matter\nC(n,r) = n! / (r!(n-r)!)\n'How many ways to choose r items from n?'\n\nExample: 8 people, how many committees of 3?\nC(8,3) = 8!/(3!×5!) = (8×7×6)/(3×2×1) = 56\n\nKey difference:\n- ABC, ACB, BAC are different permutations but the same combination\n- Combinations ≤ Permutations for the same n, r\n\nMemory trick:\n- Permutation = Position matters (arranging seats)\n- Combination = Chosen, not ordered (picking a team)\n\nPascal's Triangle gives combinations: row n, position r = C(n,r)", "probability", 2),
    ("What is Bayes' Theorem?", "Bayes' Theorem updates probabilities with new evidence.\n\nP(A|B) = P(B|A) × P(A) / P(B)\n\n'Given new evidence B, how should I update my belief about A?'\n\nComponents:\n- P(A): Prior probability (belief before evidence)\n- P(B|A): Likelihood (how likely is the evidence if A is true?)\n- P(B): Total probability of evidence\n- P(A|B): Posterior probability (updated belief after evidence)\n\nMedical test example:\n- 0.1% of population has disease → P(D) = 0.001\n- Test is 99% sensitive: P(+|D) = 0.99\n- Test is 95% specific: P(-|no D) = 0.95, so P(+|no D) = 0.05\n\nYou test positive. What's P(D|+)?\n\nP(D|+) = P(+|D) × P(D) / P(+)\nP(+) = P(+|D)P(D) + P(+|no D)P(no D)\n= 0.99 × 0.001 + 0.05 × 0.999\n= 0.00099 + 0.04995 = 0.05094\n\nP(D|+) = 0.00099 / 0.05094 ≈ 1.9%\n\nEven with a positive test, only ~2% chance of disease! (Because disease is rare.)", "probability", 4),

# ============================================================
# LINEAR ALGEBRA (15 more - target 17)
# ============================================================
    ("What is matrix multiplication?", "To multiply matrices A × B, the number of columns in A must equal the number of rows in B.\n\nIf A is m×n and B is n×p, the result C is m×p.\n\nEach element Cᵢⱼ = dot product of row i of A with column j of B.\n\nExample:\nA = [1 2]    B = [5 6]\n    [3 4]        [7 8]\n\nC₁₁ = 1×5 + 2×7 = 19\nC₁₂ = 1×6 + 2×8 = 22\nC₂₁ = 3×5 + 4×7 = 43\nC₂₂ = 3×6 + 4×8 = 50\n\nC = [19 22]\n    [43 50]\n\nImportant:\n- AB ≠ BA in general (order matters!)\n- Matrix multiplication is NOT element-wise\n- Identity matrix I: AI = IA = A (like multiplying by 1)\n- Dimensions must be compatible: (m×n)(n×p) = (m×p)", "linear_algebra", 2),
    ("What is a determinant?", "The determinant of a square matrix is a single number that tells you important properties.\n\n2×2 matrix:\n|a b|\n|c d|  = ad - bc\n\n3×3 matrix: Use expansion by minors (cofactor expansion)\n\nWhat the determinant tells you:\n- det ≠ 0: Matrix is invertible (has a unique solution to Ax = b)\n- det = 0: Matrix is singular (no inverse, system may have no or infinite solutions)\n- |det|: Scale factor of the linear transformation\n- sign of det: Positive = preserves orientation, Negative = flips\n- det = 0: Transformation collapses dimension (2D → 1D or 0D)\n\nGeometric meaning:\nFor a 2×2 matrix, |det| = area scale factor\nFor a 3×3 matrix, |det| = volume scale factor\n\nProperties:\n- det(AB) = det(A) × det(B)\n- det(A⁻¹) = 1/det(A)\n- det(Aᵀ) = det(A)\n- Swapping two rows changes the sign", "linear_algebra", 3),
    ("What are eigenvalues and eigenvectors?", "For a matrix A, an eigenvector v is a vector that only gets scaled (not rotated) when multiplied by A.\n\nAv = λv\n\nA = matrix, v = eigenvector, λ = eigenvalue (the scaling factor)\n\nExample: A = [3 1]\n         [0 2]\n\nEigenvector v₁ = [1, 0], eigenvalue λ₁ = 3\nCheck: A × [1,0] = [3,0] = 3 × [1,0] ✓\n\nEigenvector v₂ = [1, -1], eigenvalue λ₂ = 2\nCheck: A × [1,-1] = [2,-2] = 2 × [1,-1] ✓\n\nHow to find them:\n1. det(A - λI) = 0 (characteristic equation)\n2. Solve for λ (eigenvalues)\n3. For each λ, solve (A - λI)v = 0 for v (eigenvectors)\n\nApplications:\n- PageRank: Google's original algorithm uses eigenvectors\n- Vibration analysis: natural frequencies are eigenvalues\n- PCA: principal components are eigenvectors of covariance matrix\n- Quantum mechanics: observables have eigenvalues as measurement results\n- Differential equations: solutions involve eigenvalues", "linear_algebra", 4),
    ("What is a system of linear equations?", "Multiple linear equations with the same variables.\n\nExample:\n2x + y = 5\n x - y = 1\n\nSolutions: one, none, or infinitely many\n\nOne solution: lines intersect at one point\nFrom above: adding equations gives 3x = 6, x = 2, y = 1\n\nNo solution: parallel lines (same slope, different intercept)\n2x + y = 5\n2x + y = 7 (impossible!)\n\nInfinite solutions: same line (equations are multiples)\n2x + y = 5\n4x + 2y = 10\n\nMatrix form: Ax = b\n[2 1][x] = [5]\n[1 -1][y] = [1]\n\nSolving methods:\n- Substitution: solve one equation, plug into other\n- Elimination: add/subtract equations to eliminate variables\n- Matrix inverse: x = A⁻¹b (if det(A) ≠ 0)\n- Gaussian elimination: row operations to get row echelon form", "linear_algebra", 2),

# ============================================================
# MORE PHYSICS (20 more)
# ============================================================
    ("What is the work-energy theorem?", "The net work done on an object equals its change in kinetic energy.\n\nW_net = ΔKE = KE_final - KE_initial\nW = ½mv₂² - ½mv₁²\n\nWork = Force × Distance (in the direction of force)\nW = Fd·cos(θ)\n\nExample: Push a 5 kg box 3 m with 20 N of force (parallel to motion)\nW = 20 × 3 = 60 J\n\nIf the box started from rest:\n60 = ½(5)v² - 0\nv² = 24\nv = √24 ≈ 4.9 m/s\n\nKey points:\n- Work can be positive (force in direction of motion) or negative (force opposing motion)\n- No work is done if force is perpendicular to motion (carrying a box horizontally doesn't do work on it against gravity... unless you're accelerating it)\n- Friction always does negative work (slows things down)\n- The theorem connects forces (Newton's laws) to energy conservation", "physics", 3),
    ("What is the difference between series and parallel circuits?", "Series circuit: Components in a single path\n- Same current through all components\n- Voltages add up: V_total = V₁ + V₂ + V₃\n- Resistances add: R_total = R₁ + R₂ + R₃\n- One component fails → entire circuit breaks\n- More resistors → higher total resistance\n\nExample: Two 6Ω resistors in series = 12Ω total\n\nParallel circuit: Components in separate branches\n- Same voltage across all components\n- Currents add up: I_total = I₁ + I₂ + I₃\n- 1/R_total = 1/R₁ + 1/R₂ + 1/R₃\n- One component fails → others still work\n- More resistors → lower total resistance\n\nExample: Two 6Ω resistors in parallel\n1/R = 1/6 + 1/6 = 2/6 → R = 3Ω\n\nAnalogy:\n- Series: One lane road — all cars must go through each toll booth\n- Parallel: Multi-lane road — cars can take any lane, total flow increases\n\nHouse wiring uses parallel circuits so each appliance works independently.", "physics", 2),
    ("What is the difference between distance and displacement?", "Distance: Total path length traveled (scalar, always positive)\nDisplacement: Straight-line from start to end (vector, has direction)\n\nExample: You walk 3m east, then 4m north.\n- Distance = 3 + 4 = 7m\n- Displacement = √(3² + 4²) = 5m northeast\n\nRound trip: You walk 5m to the store and 5m back.\n- Distance = 10m\n- Displacement = 0m (you're back where you started!)\n\nKey differences:\n- Distance can never decrease; displacement can be zero or negative\n- Distance ≥ |displacement| always\n- Distance measures 'how much ground you covered'\n- Displacement measures 'how far you are from where you started'\n\nIn physics, displacement matters more because:\n- Velocity = displacement/time (not distance/time)\n- A race car going in circles has distance increasing but displacement cycling\n- Work depends on displacement, not distance", "physics", 1),
    ("What is thermal energy and temperature?", "Thermal energy: Total kinetic energy of all particles in an object (depends on amount of matter)\n\nTemperature: Average kinetic energy per particle (doesn't depend on amount)\n\nExample:\n- A bathtub at 40°C has MORE thermal energy than a coffee cup at 90°C\n- But the coffee has a HIGHER temperature\n\nThree temperature scales:\n- Celsius: 0°C = freezing water, 100°C = boiling water\n- Fahrenheit: 32°F = freezing, 212°F = boiling\n- Kelvin: 0 K = absolute zero (-273°C), 273 K = freezing, 373 K = boiling\n\nConversions:\n°C = (°F - 32) × 5/9\n°F = °C × 9/5 + 32\nK = °C + 273.15\n\nHeat flows from hot to cold (never the other way without work — that's the 2nd law of thermodynamics).\n\nMethods of heat transfer:\n- Conduction: direct contact (touching a hot pan)\n- Convection: fluid movement (boiling water, weather)\n- Radiation: electromagnetic waves (sun, campfire)", "physics", 2),
    ("What is electromagnetic induction?", "Moving a magnet near a wire creates a voltage (and current if the circuit is closed). This is electromagnetic induction.\n\nFaraday's Law: EMF = -dΦ/dt\nThe induced voltage equals the rate of change of magnetic flux.\n\nLenz's Law: The induced current opposes the change that created it.\n- Magnet approaching → current creates a field that repels the magnet\n- Magnet leaving → current creates a field that attracts the magnet\n\nWhat affects the induced EMF:\n- Stronger magnet → more EMF\n- Faster movement → more EMF\n- More coil turns → more EMF\n- Bigger coil area → more EMF\n\nApplications:\n- Electric generators: Spin a coil in a magnetic field → produces electricity\n- Transformers: Changing current in one coil induces voltage in another\n- Induction stoves: Changing magnetic field heats the pan directly\n- Wireless charging: Magnetic coupling between coils\n- Guitar pickups: Vibrating string changes flux → voltage → sound", "physics", 3),
    ("Explain Newton's Third Law", "For every action, there is an equal and opposite reaction.\n\nF₁₂ = -F₂₁\n\nIf object A pushes object B, object B pushes object A with the same force in the opposite direction.\n\nExamples:\n- You push on the wall → wall pushes back on you\n- Rocket expels gas downward → gas pushes rocket upward\n- Earth pulls you down → you pull Earth up (same force, Earth barely moves because F=ma and Earth has huge mass)\n- Book on table: book pushes table down (weight), table pushes book up (normal force)\n\nCommon misconceptions:\n- The forces are on DIFFERENT objects, not the same object (that's why they don't cancel out)\n- The 'equal and opposite' doesn't mean equal effects — a small car and big truck in a crash experience the same force, but very different accelerations\n- Action and reaction happen simultaneously, not one after the other\n\nWhy rockets work in space: They push gas backward, gas pushes rocket forward. No air needed — the reaction force is between the rocket and its own exhaust.", "physics", 2),

# ============================================================
# MORE CHEMISTRY (20 more)
# ============================================================
    ("What is molarity?", "Molarity (M) = moles of solute / liters of solution\n\nIt measures concentration: how much stuff is dissolved per volume.\n\nExample: 58.5g NaCl in 1 L of solution\nMoles of NaCl = 58.5 / 58.5 = 1 mol\nMolarity = 1 mol / 1 L = 1 M\n\nMaking solutions:\n- 0.5 M NaCl: dissolve 0.5 mol (29.25g) NaCl and add water to make 1 L total\n- 'Add water to' not 'add 1 L water to' — the volume includes the solute\n\nDilution formula: M₁V₁ = M₂V₂\nTo make 500 mL of 0.1 M HCl from 6 M stock:\n6 × V₁ = 0.1 × 500\nV₁ = 8.33 mL of stock solution, then dilute to 500 mL\n\nOther concentration units:\n- Molality: moles/kg solvent (doesn't change with temperature)\n- Mass%: grams solute / 100g solution\n- ppm/ppb: parts per million/billion", "chemistry", 2),
    ("What is the periodic trend for atomic radius?", "Atomic radius = size of an atom (distance from nucleus to outermost electrons)\n\nTrends:\n- Decreases left to right across a period\n  (More protons pull electrons closer, same shell)\n- Increases top to bottom down a group\n  (More electron shells = bigger atom)\n\nWhy left to right decrease:\nEach element adds a proton AND an electron. The increased nuclear charge pulls all electrons tighter, but electrons are in the same shell. Net effect: smaller.\n\nWhy top to bottom increase:\nEach row adds a new electron shell. Shell n=1 is tiny, n=6 is huge.\n\nSmallest atoms: top right (before noble gases)\nLargest atoms: bottom left\n\nSmallest: Helium (31 pm)\nLargest: Francium (270 pm) or Cesium (265 pm) [Francium is radioactive and rare]\n\nExceptions:\n- Transition metals don't shrink as fast across a period (d electrons shield poorly)\n- Lanthanide contraction: 4f electrons don't shield well, making period 6 elements smaller than expected", "chemistry", 2),
    ("What is an endothermic vs exothermic reaction?", "Exothermic: Releases energy (usually as heat)\nΔH < 0 (negative enthalpy change)\nSystem loses energy, surroundings warm up\n\nExamples:\n- Combustion (burning): C₃H₈ + 5O₂ → 3CO₂ + 4H₂O + heat\n- Rusting: 4Fe + 3O₂ → 2Fe₂O₃ + heat\n- Neutralization: HCl + NaOH → NaCl + H₂O + heat\n- Hand warmers, self-heating cans\n\nEndothermic: Absorbs energy (takes in heat)\nΔH > 0 (positive enthalpy change)\nSystem gains energy, surroundings cool down\n\nExamples:\n- Photosynthesis: 6CO₂ + 6H₂O + energy → C₆H₁₂O₆ + 6O₂\n- Dissolving NH₄NO₃ in water (cold pack)\n- Melting ice: H₂O(s) + energy → H₂O(l)\n- Thermal decomposition of CaCO₃\n\nEnergy diagram:\n- Exothermic: products lower than reactants (energy released)\n- Endothermic: products higher than reactants (energy absorbed)\n\nBoth need activation energy to start — exothermic reactions aren't automatically spontaneous.", "chemistry", 2),
    ("What are hydrogen bonds?", "Hydrogen bonds are intermolecular forces (NOT actual bonds) between molecules.\n\nThey form when H is bonded to N, O, or F and attracted to a lone pair on another N, O, or F.\n\nWhy only N, O, F? These are the most electronegative elements. They pull the shared electrons so hard that H becomes nearly positive, creating a strong dipole.\n\nStrength: About 1/10 as strong as a covalent bond, but much stronger than other intermolecular forces.\n\nWhy hydrogen bonds matter:\n- Water's high boiling point (100°C vs H₂S at -60°C)\n- Ice floats (H-bonds create an open crystal structure, less dense than liquid)\n- DNA base pairing (A-T, G-C held together by H-bonds)\n- Protein folding (stabilizes secondary structures like α-helices)\n- High surface tension of water\n- Capillary action in plants\n\nWithout hydrogen bonds:\n- Water would be a gas at room temperature\n- Life as we know it couldn't exist\n- DNA couldn't hold its double helix together", "chemistry", 3),
    ("What is stoichiometry?", "Stoichiometry = calculating quantities in chemical reactions using balanced equations.\n\nThe balanced equation tells you the mole ratios:\n2H₂ + O₂ → 2H₂O\n2 mol hydrogen reacts with 1 mol oxygen to produce 2 mol water\n\nSteps:\n1. Write balanced equation\n2. Convert given quantities to moles\n3. Use mole ratio from equation\n4. Convert to desired units\n\nExample: How many grams of H₂O from 4g of H₂?\n1. 2H₂ + O₂ → 2H₂O (already balanced)\n2. 4g H₂ × (1 mol / 2g) = 2 mol H₂\n3. 2 mol H₂ × (2 mol H₂O / 2 mol H₂) = 2 mol H₂O\n4. 2 mol H₂O × (18 g / mol) = 36 g H₂O\n\nLimiting reactant: The reactant that runs out first, determining how much product forms.\n\nIf you have 2 mol H₂ and 2 mol O₂:\nH₂ needs 1 mol O₂ (ratio 2:1), so H₂ is the limiting reactant\nO₂ is in excess (1 mol left over)", "chemistry", 3),
    ("What are the gas laws?", "Four main gas laws (all assume constant amount of gas):\n\nBoyle's Law: P₁V₁ = P₂V₂ (constant T)\nPressure and volume are inversely proportional\nSqueeze a balloon → pressure goes up\n\nCharles's Law: V₁/T₁ = V₂/T₂ (constant P)\nVolume and temperature are directly proportional\nHeat a balloon → it expands\n\nGay-Lussac's Law: P₁/T₁ = P₂/T₂ (constant V)\nPressure and temperature are directly proportional\nHeat a sealed container → pressure increases (dangerous!)\n\nAvogadro's Law: V₁/n₁ = V₂/n₂ (constant P, T)\nVolume and moles are directly proportional\nMore gas → bigger volume (at same P, T)\n\nCombined: PV = nRT (Ideal Gas Law)\n\n⚠️ Temperature must ALWAYS be in Kelvin!\nT(K) = T(°C) + 273.15\n\nThese are 'ideal' gas laws — real gases deviate at high pressure and low temperature (when molecules are close enough to interact).", "chemistry", 3),

# ============================================================
# MORE ALGEBRA (15 more)
# ============================================================
    ("What is a rational expression?", "A rational expression is a fraction where numerator and/or denominator are polynomials.\n\nExamples:\n- (x+1)/(x-2)\n- (3x²+2x)/(x²-4)\n- 5/(x+3)\n\nKey rule: The denominator cannot be zero!\n(x+1)/(x-2) is undefined at x = 2\n\nSimplifying: Factor and cancel common factors\n(x²-4)/(x+2) = (x-2)(x+2)/(x+2) = x-2 (for x ≠ -2)\n\nOperations:\n- Multiply: (a/b) × (c/d) = (ac)/(bd)\n- Divide: (a/b) ÷ (c/d) = (a/b) × (d/c) = (ad)/(bc)\n- Add: Find common denominator, then add numerators\n  a/b + c/d = (ad + bc)/(bd)\n\nDomain restrictions: Set each denominator factor to zero and exclude those x-values.", "algebra", 3),
    ("What is the difference between an equation and an expression?", "Expression: A combination of numbers, variables, and operations (no equals sign)\n- 3x + 5\n- x² - 4\n- 2(x + 1)\n\nYou can simplify expressions, but you can't solve them.\n\nEquation: A statement that two expressions are equal (has an equals sign)\n- 3x + 5 = 14\n- x² - 4 = 0\n- 2(x + 1) = 10\n\nYou can solve equations (find the values of x that make it true).\n\nAnalogy:\n- Expression: '3x + 5' is like a recipe — you can evaluate it for any x\n- Equation: '3x + 5 = 14' is like a question — for what x is this true?\n\nInequality: Like an equation but with <, >, ≤, ≥\n- 3x + 5 > 14 (x > 3)\n\nFunction: An expression with a name\n- f(x) = 3x + 5 (assigns exactly one output to each input)", "algebra", 1),
    ("How do you factor a quadratic?", "For ax² + bx + c, find two numbers that:\n- Multiply to ac\n- Add to b\n\nExample: x² + 5x + 6\nNeed: two numbers that multiply to 6 and add to 5\n2 × 3 = 6 and 2 + 3 = 5\nx² + 5x + 6 = (x + 2)(x + 3)\n\nExample: x² - 7x + 12\nNeed: multiply to 12, add to -7\n-3 × -4 = 12 and -3 + -4 = -7\nx² - 7x + 12 = (x - 3)(x - 4)\n\nWhen a ≠ 1: 2x² + 7x + 3\nNeed: multiply to 2×3 = 6, add to 7\n1 × 6 = 6 and 1 + 6 = 7\nSplit: 2x² + x + 6x + 3\nGroup: x(2x + 1) + 3(2x + 1)\nFactor: (2x + 1)(x + 3)\n\nIf factoring doesn't work cleanly → use the quadratic formula\nAlways check: expand your answer to verify!", "algebra", 2),
    ("What is the difference between domain and range?", "Domain: All possible INPUT values (x-values)\nRange: All possible OUTPUT values (y-values)\n\nFor f(x) = x²:\n- Domain: All real numbers (any x works)\n- Range: [0, ∞) (squares are never negative)\n\nFor f(x) = 1/x:\n- Domain: All reals except x = 0 (can't divide by zero)\n- Range: All reals except y = 0 (1/x never equals 0)\n\nFor f(x) = √x:\n- Domain: [0, ∞) (can't take square root of negative)\n- Range: [0, ∞) (square root is never negative)\n\nFinding domain restrictions:\n1. Denominator ≠ 0\n2. Square root of non-negative\n3. Logarithm of positive numbers only\n\nInterval notation:\n- All reals: (-∞, ∞)\n- x > 3: (3, ∞)\n- x ≤ 5: (-∞, 5]\n- 0 < x ≤ 10: (0, 10]", "algebra", 2),

# ============================================================
# MORE CALCULUS (15 more)
# ============================================================
    ("What is the power rule?", "The power rule is the most common differentiation rule:\n\nd/dx(xⁿ) = n·xⁿ⁻¹\n\nBring the exponent down, subtract 1 from the exponent.\n\nExamples:\n- d/dx(x⁵) = 5x⁴\n- d/dx(x²) = 2x\n- d/dx(x) = 1x⁰ = 1\n- d/dx(x⁻²) = -2x⁻³\n- d/dx(√x) = d/dx(x^(1/2)) = ½x^(-1/2) = 1/(2√x)\n- d/dx(1/x³) = d/dx(x⁻³) = -3x⁻⁴ = -3/x⁴\n\nWith constants:\n- d/dx(3x⁴) = 12x³\n- d/dx(-5x²) = -10x\n- d/dx(7) = 0 (constant)\n\nThe power rule works for ANY real exponent, not just integers!\nFractional, negative, even irrational exponents all work.", "calculus", 1),
    ("What is integration by substitution?", "Substitution (u-substitution) is the reverse of the chain rule for integration.\n\nIf you see a function and its derivative, substitute u for the inner function.\n\nSteps:\n1. Choose u = inner function\n2. Find du = u'dx\n3. Substitute, simplify, integrate\n4. Substitute back to x\n\nExample: ∫ 2x·(x²+1)³ dx\n\nLet u = x² + 1, then du = 2x dx\n\n∫ 2x·(x²+1)³ dx = ∫ u³ du = u⁴/4 + C = (x²+1)⁴/4 + C\n\nCheck: d/dx[(x²+1)⁴/4] = 4(x²+1)³·2x/4 = 2x(x²+1)³ ✓\n\nExample: ∫ cos(3x) dx\nLet u = 3x, du = 3dx, dx = du/3\n∫ cos(u) · du/3 = ⅓ sin(u) + C = ⅓ sin(3x) + C\n\nTip: Look for a function multiplied by its derivative (or a constant multiple of it). That's your u.", "calculus", 3),
    ("What is a related rates problem?", "Related rates: Two quantities change over time, connected by an equation. Find how fast one changes given the other's rate.\n\nGeneral approach:\n1. Draw a picture, label variables\n2. Write an equation relating the variables\n3. Differentiate both sides with respect to time (t)\n4. Plug in known values and solve\n\nClassic example: A ladder 10 ft long leans against a wall. The bottom slides away at 1 ft/s. How fast is the top sliding down when the bottom is 6 ft from the wall?\n\n1. x = distance from wall to bottom, y = height of top\n2. x² + y² = 100 (Pythagorean theorem)\n3. Differentiate: 2x(dx/dt) + 2y(dy/dt) = 0\n4. When x = 6: y = √(100-36) = 8, dx/dt = 1\n   2(6)(1) + 2(8)(dy/dt) = 0\n   12 + 16(dy/dt) = 0\n   dy/dt = -12/16 = -3/4 ft/s\n\nThe top slides down at 3/4 ft/s (negative because y is decreasing).", "calculus", 4),
    ("What is optimization in calculus?", "Optimization: Finding the maximum or minimum value of a function.\n\nSteps:\n1. Write the function to optimize (objective function)\n2. Write a constraint equation (if applicable)\n3. Use the constraint to reduce to one variable\n4. Find critical points: f'(x) = 0\n5. Use the second derivative test or endpoints to determine max/min\n\nClassic example: You have 100 ft of fence for a rectangular garden against a wall (no fence on the wall side). Maximize the area.\n\n1. Area = xy (garden against wall, 3 sides of fence)\n2. Constraint: x + 2y = 100 → x = 100 - 2y\n3. A(y) = y(100 - 2y) = 100y - 2y²\n4. A'(y) = 100 - 4y = 0 → y = 25\n5. A''(y) = -4 < 0 → maximum\n   x = 100 - 50 = 50\n   Max area = 50 × 25 = 1250 ft²\n\nThe garden is 50 ft wide and 25 ft deep.", "calculus", 4),

# ============================================================
# MORE BIOLOGY (10 more)
# ============================================================
    ("What is the cell cycle?", "The cell cycle is the sequence of events from one cell division to the next.\n\nInterphase (90% of the cycle):\n1. G1 (Gap 1): Cell grows, makes proteins, does its job\n2. S (Synthesis): DNA is replicated (each chromosome → 2 sister chromatids)\n3. G2 (Gap 2): Cell prepares for division (more growth, checks DNA)\n\nM Phase (10%):\n4. Mitosis: Nuclear division (PMAT)\n5. Cytokinesis: Cytoplasm divides, two daughter cells form\n\nCheckpoints:\n- G1 checkpoint: Is the cell big enough? Is DNA damaged? → Go or G0 (resting)\n- G2 checkpoint: Is DNA fully replicated? Any damage?\n- M checkpoint: Are chromosomes properly aligned?\n\nIf checkpoints fail → cancer (uncontrolled cell division)\nG0 phase: Cells that aren't dividing (neurons, muscle cells). Some can re-enter G1, others are stuck permanently.", "biology", 3),
    ("What is the difference between mRNA, tRNA, and rRNA?", "mRNA (messenger RNA):\n- Carries genetic code from DNA to ribosome\n- Made during transcription\n- Contains codons (3-base sequences that specify amino acids)\n- Short-lived, degraded after translation\n- Start codon: AUG, Stop codons: UAA, UAG, UGA\n\ntRNA (transfer RNA):\n- Delivers amino acids to the ribosome\n- Has an anticodon that matches mRNA codon (complementary)\n- Cloverleaf shape, L-shaped 3D structure\n- Each tRNA carries one specific amino acid\n- Example: tRNA with anticodon UAC carries Methionine\n\nrRNA (ribosomal RNA):\n- Structural and catalytic component of ribosomes\n- Ribosome = rRNA + proteins\n- Peptidyl transferase (makes peptide bonds) is a ribozyme (RNA enzyme)\n- Most abundant RNA type (~80% of cellular RNA)\n- Eukaryotic: 80S ribosome (60S + 40S subunits)\n- Prokaryotic: 70S ribosome (50S + 30S subunits)\n\nThe ribosome reads mRNA, tRNA brings amino acids, rRNA catalyzes bond formation. Together they make proteins.", "biology", 2),

# ============================================================
# MORE CS (10 more)
# ============================================================
    ("What is the difference between HTTP and HTTPS?", "HTTP: Hypertext Transfer Protocol — how web browsers and servers communicate.\nHTTPS: HTTP + TLS/SSL encryption — the secure version.\n\nHTTP:\n- Data sent in plain text\n- Anyone on the network can read it\n- Port 80\n- No verification of server identity\n\nHTTPS:\n- Data encrypted with TLS (Transport Layer Security)\n- Even if intercepted, data is unreadable\n- Port 443\n- Server identity verified by certificate authority\n- Green lock icon in browser\n\nHow HTTPS works (simplified):\n1. Browser connects to server\n2. Server sends its SSL certificate (signed by a trusted authority)\n3. Browser verifies the certificate\n4. Both sides generate session keys (using asymmetric encryption)\n5. All subsequent data encrypted with session keys (symmetric, faster)\n\nWhy it matters:\n- Protects passwords, credit cards, personal data\n- Prevents man-in-the-middle attacks\n- Google ranks HTTPS sites higher\n- Modern browsers flag HTTP sites as 'Not Secure'\n\nHTTPS doesn't mean the site is trustworthy — it just means the connection is encrypted.", "cs", 2),
    ("What is dynamic programming?", "Dynamic programming (DP) solves problems by breaking them into overlapping subproblems and storing results to avoid recomputation.\n\nTwo approaches:\n1. Top-down (memoization): Recursive, cache results\n2. Bottom-up (tabulation): Iterative, fill table from smallest to largest\n\nClassic example: Fibonacci\nNaive: fib(n) = fib(n-1) + fib(n-2) → O(2ⁿ) (exponential!)\n\nWith memoization: O(n)\ndef fib(n, memo={}):\n    if n in memo: return memo[n]\n    if n <= 1: return n\n    memo[n] = fib(n-1, memo) + fib(n-2, memo)\n    return memo[n]\n\nWith tabulation: O(n)\ndef fib(n):\n    dp = [0, 1]\n    for i in range(2, n+1):\n        dp.append(dp[i-1] + dp[i-2])\n    return dp[n]\n\nWhen to use DP:\n- Overlapping subproblems (same subproblem solved multiple times)\n- Optimal substructure (optimal solution contains optimal sub-solutions)\n\nClassic DP problems: knapsack, longest common subsequence, edit distance, coin change, shortest path", "cs", 4),
]

if __name__ == "__main__":
    print(f"Supplement2 has {len(SUPPLEMENT2)} examples")
